baseurl: https://blog.gitea.io/
languageCode: en-us
title: Blog
theme: gitea
disqusShortname: gitea

defaultContentLanguage: en-us
defaultContentLanguageInSubdir: true
enableMissingTranslationPlaceholders: true

permalinks:
  post: /:year/:month/:title/
  doc: /:slug/
  page: /:slug/
  default: /:slug/

params:
  description: Git with a cup of tea
  author: The Gitea Authors
  website: https://blog.gitea.io

menu:
  page:
    - name: Website
      url: https://gitea.io/en-us/
      weight: 10
      pre: home
    - name: Docs
      url: https://docs.gitea.io/en-us/
      weight: 20
      pre: question
    - name: Blog
      url: /
      weight: 30
      pre: rss
      post: active
    - name: Code
      url: https://code.gitea.io/
      weight: 40
      pre: code
    - name: Downloads
      url: https://dl.gitea.io/
      weight: 50
      pre: download
    - name: GitHub
      url: https://github.com/go-gitea/
      weight: 60
      pre: github

# languages:
#   en-us:
#     weight: 0
#     languageName: English
#   zh-cn:
#     weight: 1
#     languageName: 中文(简体)
#     menu:
#       page:
#         - name: 网站
#           url: https://gitea.io/zh-cn/
#           weight: 10
#           pre: home
#         - name: 文档
#           url: https://docs.gitea.io/zh-cn/
#           weight: 20
#           pre: question
#         - name: 博客
#           url: /
#           weight: 30
#           pre: rss
#           post: active
#         - name: 导入
#           url: https://code.gitea.io/
#           weight: 40
#           pre: code
#         - name: 下载
#           url: https://dl.gitea.io/
#           weight: 50
#           pre: download
#         - name: GitHub
#           url: https://github.com/go-gitea/
#           weight: 60
#           pre: github
